### ISSUE TITLE
What do you like or dislike on Doctrine?

### ISSUE THREAD

**Issue by TomasVotruba** [DeprecatedPackages/PlaygroundORM#1]
Feedback from chatting with people

## Like or use

- Mapper
- Entity

## Dislike or don't use 
 
- Yaml Mapping Driver
- Annotations Mapping
- Any driver without autocomplete
- Event Manager

## Misses

- Final Entities

**Comment by enumag** [comment]
Personally I mostly like Doctrine. The main things I don't like are those that often cause beginners to use it badly.

1) EntityRepository::getEntityManager() should be internal or private. It should not be used by custom repository except for very special cases (I only have one use-case at the moment).
2) Calling flush during flush (usually from event listener) should raise an exception. It can couse some very nasty errors.
3) Calling $entity->getRelatedEntity() should load the related entities for the entire result like Nextras ORM for example. Current behavior easily leads to lot of duplicated queries and fixing it correctly in *:N cases requires [advanced knowledge](http://ocramius.github.io/blog/doctrine-orm-optimization-hydration/).

**Comment by TomasVotruba** [comment]
Notes from Honza Kuchař:

### Missing 

- automatic quoting strategy
- automatic aliases

**Comment by simara-svatopluk** [comment]
## Like
* Mapping
* DQL (joinning not related entities++)
* Hydration options
* yaml driver

## Dislike
* Entity lazy loading - cause tones of performance issues and modeling misunderstanding

## Missing
* Mapping collections of value objects (embedded) without entities

**Comment by TomasVotruba** [comment]
Just to let you know, I [wrote down my feelings about Doctrine ORM](https://www.tomasvotruba.cz/blog/2017/03/27/why-is-doctrine-dying/).

In recent couple of months I realized, I don't see value in ORMs as pattern useful in the future, so this project is not interesting for me anymore.

I'll deprecated it (keeping alive for now, just in another organization). Let me know if you'd like to develop it.
